heat_template_version: 2013-05-23

description: A Heat Template

parameters:

resources:
  ssh_key:
    type: "OS::Nova::KeyPair"
    properties:
      name: { get_param: "OS::stack_id" }
      save_private_key: true

  random_string:
    type: OS::Heat::RandomString
outputs:
  private_key:
    value: { get_attr: [ssh_key, private_key] }
    description: SSH Private Key
